apiVersion: apps/v1    
kind: Deployment    
metadata:    
  name: usermodule-ui    
  labels:    
    app: usermodule-ui 
spec:    
  replicas: 2    
  selector:    
    matchLabels:    
      app: usermodule-ui   
  strategy:    
    rollingUpdate:    
      maxSurge: 25%    
      maxUnavailable: 25%    
    type: RollingUpdate    
  template:    
    metadata:    
      labels:    
        app: usermodule-ui    
    spec:    
      containers:    
      - image: 183454673550.dkr.ecr.ap-south-1.amazonaws.com/usermodule-ui:BUILDNUMBER    
        imagePullPolicy: Always    
        name: usermodule-ui   
        ports:    
        - containerPort: 80    
          protocol: TCP    
      imagePullSecrets:    
      - name: aws-ecr  